FROM node:18-alpine

ARG PORT

ENV PORT $PORT
ENV MONGO_USERNAME $MONGO_USERNAME
ENV MONGO_PASSWORD $MONGO_PASSWORD
ENV MONGO_SERVER $MONGO_SERVER
ENV MONGO_APP_NAME $MONGO_APP_NAME
ENV AI_API $AI_API
ENV OPENAI_API_KEY $OPENAI_API_KEY
ENV OPENAI_MODEL $OPENAI_MODEL
ENV ANTHROPIC_API_KEY $ANTHROPIC_API_KEY
ENV ANTHROPIC_MODEL $ANTHROPIC_MODEL

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production
COPY lib lib
COPY server.js ./
COPY entrypoint.sh ./

# Make the entrypoint script executable
RUN chmod +x entrypoint.sh

EXPOSE $PORT

ENTRYPOINT ["./entrypoint.sh"]
