FROM node:18-alpine

ARG PORT
ARG MONGO_USERNAME
ARG MONGO_PASSWORD
ARG MONGO_SERVER
ARG MONGO_APP_NAME
ARG OPENAI_API_KEY
ARG OPENAI_MODEL

ENV PORT $PORT
ENV MONGO_USERNAME $MONGO_USERNAME
ENV MONGO_PASSWORD $MONGO_PASSWORD
ENV MONGO_SERVER $MONGO_SERVER
ENV MONGO_APP_NAME $MONGO_APP_NAME
ENV OPENAI_API_KEY $OPENAI_API_KEY
ENV OPENAI_MODEL $OPENAI_MODEL

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production
COPY lib lib
COPY server.js ./

EXPOSE $PORT

ENTRYPOINT ["node","server.js"]
